### ISSUE TITLE
[Sprint] Docs: configuration

### ISSUE THREAD

**Issue by deepkyu** [Nota-NetsPresso/netspresso-trainer#145]
## Description

- Add an detailed explanation about training configuration

## Checklists

- [x] I would create a corresponding branch for this issue from the designated (mostly `master`) branch.
- [x] This issue only contains a preceding agreement between project owners.

**Comment by illian01** [comment]
@deepkyu 
Great! I think it is good idea to upload gradio demo into Hugging Face Spaces.
Users can experience demo just by accessing the link.
But, embedding may takes a time, I think it would be better to put a guide link first, and replace it later.

**Comment by deepkyu** [comment]
Blocked by #150
