### ISSUE TITLE
[Sprint] Add an easy-to-use Colab demo

### ISSUE THREAD

**Issue by deepkyu** [Nota-NetsPresso/netspresso-trainer#146]
## Description

- Add Colab demo to showcase the training and PyNetsPresso integration process

## Checklists

- [ ] I would create a corresponding branch for this issue from the designated (mostly `master`) branch.
- [x] This issue only contains a preceding agreement between project owners.

**Comment by deepkyu** [comment]
Blocked by #153 
- Fix the demo after applying pip package installation

**Comment by deepkyu** [comment]
Hi @illian01,

I checked that `netspresso-trainer==0.0.7` works with our Hugging Face Space demo.
You may start to replace the training colab demo with the public package version.

**Comment by deepkyu** [comment]
Blocked by #171

**Comment by illian01** [comment]
Blocked by #178

**Comment by illian01** [comment]
@deepkyu 
I modified [colab tutorial](https://colab.research.google.com/drive/1RBKMCPEa4x-4X31zqzTS8WgQI9TQt3e-?usp=sharing) to select most configs by dropdowns.
Please check this when you have time.

**Comment by deepkyu** [comment]
@illian01 
I think it's time to introduce this colab example in README and our docs.
Plz add at README or `Getting started` in our docs if you have time :)
Thanks for hard work
