### ISSUE TITLE
[Sprint] Add classification models from NetsPresso Searcher

### ISSUE THREAD

**Issue by deepkyu** [Nota-NetsPresso/netspresso-trainer#172]
## Description

- Add NetsPresso classification models from https://docs.netspresso.ai/docs/performance-benchmark
  - Only models supported in NetsPresso would be incldued.

## Checklists

- [x] I would create a corresponding branch for this issue from the designated (mostly `dev`) branch.
- [x] This issue only contains a preceding agreement between project owners.

**Comment by deepkyu** [comment]
This issue has been moved from 3Q to 4Q milestone.

**Comment by illian01** [comment]
Add MixNet in #229
