### ISSUE TITLE
[Feature Request] create_transform_segmentation function is too strict

### ISSUE THREAD

**Issue by illian01** [Nota-NetsPresso/netspresso-trainer#174]
- [x] I have searched to see if a similar issue already exists.

**Is there any feature that you would like to add?**  
There is `model_name` check before return tranform function.

https://github.com/Nota-NetsPresso/netspresso-trainer/blob/0049a9b48885b3c48cb674c6040939613caa79da/src/netspresso_trainer/dataloaders/segmentation/transforms.py#L111-L121

This is too strict, and this raise error when the `model_name` contains `_graphmodule` or new model is added.
I think it's okay to remove `model_name` check except `pidnet`.

**Is there any suggestion (or solution) to solve this issue?**  
I think it would be better to remove `model_name` check until future update of augmentation features.

**Additional context**  
All other contexts or screenshots are welcome.

**Comment by deepkyu** [comment]
@illian01 
This should be fixed! Thx!
