### ISSUE TITLE
[Sprint] Compatibility matrix for NetsPresso ecosystem

### ISSUE THREAD

**Issue by deepkyu** [Nota-NetsPresso/netspresso-trainer#245]
## Description

- Add NetsPresso compatibility matrix

## Checklists

- [ ] I would create a corresponding branch for this issue from the designated (mostly `dev`) branch.
- [x] This issue only contains a preceding agreement between project owners.

**Comment by deepkyu** [comment]
Decided to save artifacts at Google Drive to share with teams of non-developers

**Comment by deepkyu** [comment]
Code impl at other repository.
This issue tracks the status of the dev status of other repository.

**Comment by illian01** [comment]
This issue completed at other private repository.
