### ISSUE TITLE
[BUG] Local classification dataset load error in DataSampler

### ISSUE THREAD

**Issue by illian01** [Nota-NetsPresso/netspresso-trainer#251]
### Describe the bug

I found two cases error.

case 1)
https://github.com/Nota-NetsPresso/netspresso-trainer/blob/5a97c0756494e61ab14dce241dcd1b17e2b13aee/src/netspresso_trainer/dataloaders/classification/dataset.py#L122-L125

In this for loop, `file` variable becomes `generator` type. This cause error when access `file.name`.

```
file
> <generator object Path.glob at 0x7fb503011dd0>
```

case 2)
https://github.com/Nota-NetsPresso/netspresso-trainer/blob/5a97c0756494e61ab14dce241dcd1b17e2b13aee/src/netspresso_trainer/dataloaders/classification/dataset.py#L117-L122

`is_file_dict` seems checking function which compare directory path and file path. But this produces error in validation dataset sampling phase, because `file_or_dir_to_idx` value still contains file information about training samples.
```
file_or_dir_to_idx # containing training samples info
> {'n03792972_3671.JPEG': 727, 'n04357314_4256.JPEG': 809, 'n02965783_127.JPEG': 575, 'n04465501_16825.JPEG': 288, 'n09246464_5059.JPEG': 358, 'n03837869_2881.JPEG': 698, 'n03661043_17566.JPEG': 686, 'n02391049_5276.JPEG': 79, 'n02869837_7669.JPEG': 804, 'n03895866_109869.JPEG': 256, 'n01855672_14191.JPEG': 419, 'n03877472_14650.JPEG': 758, 'n03832673_3919.JPEG': 551, 'n04458633_15039.JPEG': 699, ...}
image_dir
> PosixPath('/ssd1/junho.shin/data/IMAGENET1K/images/valid')
```

I found `load_data` of `ClassificationDataSampler` is quite different with `DetectionDataSampler` and `SegmentationDataSampler`. 
I think `ClassificationDataSampler` should be changed as others.

https://github.com/Nota-NetsPresso/netspresso-trainer/blob/5a97c0756494e61ab14dce241dcd1b17e2b13aee/src/netspresso_trainer/dataloaders/detection/dataset.py#L53-L83

https://github.com/Nota-NetsPresso/netspresso-trainer/blob/5a97c0756494e61ab14dce241dcd1b17e2b13aee/src/netspresso_trainer/dataloaders/segmentation/dataset.py#L54-L80

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Execute trainer with local classification datasets.

### System Info

```shell
Current dev branch
```

**Comment by deepkyu** [comment]
Thanks for checking out
