### ISSUE TITLE
[Documentation] Wrong links in docs

### ISSUE THREAD

**Issue by aychun** [Nota-NetsPresso/netspresso-trainer#416]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues.

### Please describe a documentation issue.

The [Model - Overview](https://github.com/Nota-NetsPresso/netspresso-trainer/blob/dev/docs/components/model/overview.md) page has outdated links. (Models and losses page)

### Is there any alternative or fix suggestion to make it better?

Fix them to point to the markdown files instead.

### Will you help us by submitting a PR?

- [X] I will submit a PR about this issue.

**Comment by illian01** [comment]
@aychun Thank you for your report. 👍 
Can you more specifically explain what is outdated links?

**Comment by aychun** [comment]
I used the term outdated assuming there was a change in the file hierarchy in the past. I believe the models and losses page in the model - overview file are supposed to mean `docs/models/overview.md` and `docs/components/model/losses.md` correspondingly.

**Comment by aychun** [comment]
@illian01 
I thought the links are meant to point to the markdown files in the repository, my apologies for the confusion.
