### ISSUE TITLE
[Feature Request] Separate the post processor configs from head.params  

### ISSUE THREAD

**Issue by aychun** [Nota-NetsPresso/netspresso-trainer#425]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues.

### Is there any feature that you would like to add?

Remove the post processor configurations from head.params and stored them at a different level.  

### Is there any suggestion (or solution) to solve this issue?

Update the sample model config files and the source code for post processors accordingly. 

### Additional context.

I will submit a PR for this change once I finish working on the yolo-fastest model. I think it's more natural for the post-processors to be placed in the same level as the `architecture` field in model configs, but I would love to get your approval to this proposal first @illian01 

### Will you help us by submitting a PR?

- [X] I will submit a PR about this issue.

**Comment by illian01** [comment]
Good! I agree with your opinion. It would be better if there is `postprocessor` field.
If you have time to take on this task later, please reply back in the comments.

**Comment by hglee98** [comment]
@illian01 @aychun I leave this comment as I think I can work on the issue above! I'll let you know the progress asap if I have a time to work on this issue😊

**Comment by illian01** [comment]
@hglee98 
Thank you for taking this issue. 👍
