### ISSUE TITLE
[Feature Request] Add support for RT-DETR

### ISSUE THREAD

**Issue by hglee98** [Nota-NetsPresso/netspresso-trainer#480]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues.

### Is there any feature that you would like to add?

Add support for the [RT-DETR](https://github.com/lyuwenyu/RT-DETR)

### Is there any suggestion (or solution) to solve this issue?

- Implement Efficient Hybrid Encoder, Uncertainty-minimal Query selection 
- Implement Auxiliary Loss, denoising training features
- Implement corresponding data augmentation pipeline to reproduce the results from the paper
- Reproduce the official results 
- Add variants for the model

### Will you help us by submitting a PR?

- [X] I will submit a PR about this issue.

**Comment by illian01** [comment]
Closed as completed
